# Generated by Django 3.1.2 on 2020-11-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_abrev', models.CharField(max_length=3)),
                ('league', models.CharField(max_length=7)),
                ('inaug', models.CharField(max_length=7)),
                ('end', models.CharField(max_length=7)),
                ('years', models.IntegerField()),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('w_l_pct', models.DecimalField(decimal_places=1, max_digits=3)),
                ('playoffs', models.IntegerField()),
                ('division', models.IntegerField()),
                ('conference', models.IntegerField()),
                ('championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('games', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('minutes_played', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field_goals', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('field_goals_pct', models.DecimalField(decimal_places=3, max_digits=3)),
                ('three_pts', models.IntegerField()),
                ('three_pts_attempted', models.IntegerField()),
                ('three_pts_pct', models.DecimalField(decimal_places=3, max_digits=3)),
                ('two_pts', models.IntegerField()),
                ('two_pts_attempted', models.IntegerField()),
                ('two_pts_pct', models.DecimalField(decimal_places=3, max_digits=3)),
                ('effective_fg_pct', models.DecimalField(decimal_places=3, max_digits=3)),
                ('points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('free_throws', models.DecimalField(decimal_places=1, max_digits=3)),
                ('free_throws_attempted', models.DecimalField(decimal_places=1, max_digits=3)),
                ('free_throws_pct', models.DecimalField(decimal_places=3, max_digits=3)),
                ('off_reb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('def_reb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('total_reb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('assists', models.DecimalField(decimal_places=1, max_digits=3)),
                ('steals', models.DecimalField(decimal_places=1, max_digits=3)),
                ('blocks', models.DecimalField(decimal_places=1, max_digits=3)),
                ('turnovers', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pers_fouls', models.DecimalField(decimal_places=1, max_digits=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerDB.team')),
            ],
        ),
    ]
