# Generated by Django 3.1.2 on 2020-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='field_goals',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='field_goals_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
