# Generated by Django 3.1.2 on 2020-11-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerDB', '0003_auto_20201105_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='effective_fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='three_pts_pct',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='two_pts_pct',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
