# Generated by Django 3.1.2 on 2020-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerDB', '0004_auto_20201105_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='def_reb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='effective_fg_pct',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='field_goals',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='field_goals_attempted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='field_goals_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='free_throws',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='free_throws_attempted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='free_throws_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='minutes_played',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='off_reb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='pers_fouls',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='steals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='three_pts',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='three_pts_attempted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='three_pts_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_reb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='turnovers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='two_pts',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='two_pts_attempted',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='two_pts_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
